"" Plug

" Download Plug if it doesn't exist
if empty(glob("~/.vim/autoload/plug.vim"))
    execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.github.com/junegunn/vim-plug/master/plug.vim'
endif

set nocompatible " be iMproved

"" Plugins

call plug#begin('~/.vim/plugged/')

Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'ivalkeen/nerdtree-execute', { 'on': 'NERDTreeToggle' }
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/syntastic'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'Shougo/neocomplete'
Plug 'terryma/vim-multiple-cursors'
Plug 'othree/html5.vim'
Plug 'hail2u/vim-css3-syntax'
Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'elzr/vim-json', { 'for': ['json', 'jsonp'] }
Plug 'mxw/vim-jsx', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'posva/vim-vue'
Plug 'jwalton512/vim-blade'
Plug 'sjl/gundo.vim'
Plug 'fatih/vim-go'

" Colorschemes
" Plugin 'tomasr/molokai'
Plug 'gosukiwi/vim-atom-dark'

call plug#end()



"" Stuff

set ffs=unix
let mapleader=","
if has("syntax")
  "syntax on
endif

" Jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Set utf8 as standard encoding
set encoding=utf8

" Undo levels
set undolevels=1000

" Enable mouse support
set mouse=a

" Enable modelines
set modelines=1

" Set mapping delay and key code delays
" http://www.johnhawthorn.com/2012/09/vi-escape-delays/
set timeoutlen=400
set ttimeoutlen=0



"" Syntax highlighting

" Enable syntax
syntax enable



"" Colors

set t_Co=256

colorscheme atom-dark-256
" colorscheme molokai

" Color for line numbers
highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE

" Color for fold column
highlight foldcolumn term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE

" Color for vertical splits ("border")
highlight VertSplit ctermfg=bg ctermbg=bg

" Color for cursor column
highlight CursorColumn term=reverse cterm=NONE ctermbg=236 ctermfg=none gui=NONE guibg=#293739 guifg=fg

" Color for cursor line
highlight CursorLine term=NONE cterm=NONE ctermbg=235 ctermfg=NONE gui=NONE guibg=#293739 guifg=fg

" Color for syntax errors
highlight Error term=NONE cterm=NONE ctermbg=88 ctermfg=231 gui=NONE guibg=#870000 guifg=#ffffff



"" Swap and backup

set nobackup
set swapfile

" Don't pollute my project with swap files
set directory=~/.local/share/vim/swap



"" Sessions

" Don't store global and local values in sessions
set ssop-=options

" Don't store folds
set ssop-=folds



"" Navigation

" Highlight current line.
set cursorline

" Highlight current column
set cursorcolumn

" Color the 81st column
set colorcolumn=81

" Lines to the cursor when scrolling with j/k
set scrolloff=5

" Underscores denote words
set iskeyword-=_

" Easier window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Next/prev tab with ctrl+left/right
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>

" New tab abbreviation
ca tn tabnew

" Quick exit to normal mode
inoremap jj <ESC>
inoremap jk <ESC>

" Quick save and quick exit
nmap <CR> :update<CR>
nnoremap <leader>s :update<CR>
nnoremap <leader>q :q<CR>

" highlight last inserted text
nnoremap gV `[v`]



"" Splits and tabs

" Open split panes to right and bottom
set splitbelow
set splitright

" Increase tab limit for the -p command option
set tabpagemax=50



"" Search

" Highlight search results
set hlsearch
highlight Search cterm=underline

" Search as you type
set incsearch

" Ignore case
set ignorecase

" Do not ignore case if we input a capital letter
set smartcase

" Show matching brackets on cursor hover
set showmatch

" Clear search highlighting
nnoremap <leader>/ :nohlsearch<CR>
nnoremap <leader>7 :nohlsearch<CR>
nnoremap <leader><space> :nohlsearch<CR>

" Center the search result vertically
nnoremap n nzz
nnoremap N Nzz



"" Line numbers

" Show (relative) lines numbers
set number
set relativenumber
set numberwidth=6

" Toggle absolute and relative line numbers
function! NumberToggle()
    if(&relativenumber == 1)
        set number
        set norelativenumber
    else
        set number
        set relativenumber
    endif
endfunc

nnoremap <C-n> :call NumberToggle()<cr>

"Toggle line numbers with CTRL+n x 2
":nmap <C-N><C-N> :set invnumber<CR>

"Absolute numbers in insert mode, relative numbers in normal mode
autocmd InsertEnter * :set norelativenumber
autocmd InsertLeave * :set relativenumber



"" File name completion and tabbing

set wildmode=longest:full
set wildmenu



"" Tabs for indenting

" Dont expand tabs to spaces, and set tab size
"set noexpandtab
"set tabstop=8



"" Spaces for indenting

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4



"" UI

" Always show the status line
set laststatus=2

" Show non-text characters
set list lcs=tab:·\ ,trail:∑,nbsp:%



"" Folding

" Don't fold by default
set nofoldenable

" Fold based on indent
set foldmethod=indent

" Deepest fold is 10 levels
set foldnestmax=10
set foldlevel=1
set foldcolumn=2



"" JavaScript

autocmd FileType javascript setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2



"" Git commits

" Force the cursor onto a new line after 72 characters
autocmd FileType gitcommit set textwidth=72

" Color the 73rd column
autocmd FileType gitcommit set colorcolumn=73



"" CtrlP

let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_custom_ignore = '\vnode_modules/|vendor/'

nnoremap <leader>f :CtrlP<CR>
nnoremap <leader>b :CtrlPBuffer<CR>



"" NERDTree

" Toggle
map <F2> :NERDTreeToggle<CR>

" Open NERDTree if vim starts without any files specified
" autocmd vimenter * if !argc() | NERDTree | endif

" Close vim if NERDTree is the only window left open
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

"Show hidden files in NERDTree
let NERDTreeShowHidden=1



"" NERDCommenter

let NERDSpaceDelims = 1

" Blade comments
let g:NERDCustomDelimiters = {
    \ 'blade': { 'left': '{{--', 'right': '--}}','leftAlt': '<!--', 'rightAlt': '-->' }
\ }



"" SnipMate

" let g:snipMate = {}
" let g:snipMate.no_default_aliases=1



"" UltiSnip
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"



" Indentation

" Autoindent
set autoindent



"" Paste

" Toggle paste mode
nnoremap <F3> :set invpaste paste?<CR>
set pastetoggle=<F3>
"set showmode



"" vim-airline

" Use powerline fonts to show powerline symbols. Needs a patched font
let g:airline_powerline_fonts = 1

" Set airline theme. Default behavior is to match the colorscheme.
let g:airline_theme='molokai'



"" Vim-php-cs-fixer

" If php-cs-fixer is in $PATH, you don't need to define line below
" let g:php_cs_fixer_path = "~/php-cs-fixer.phar" " define the path to the php-cs-fixer.phar
let g:php_cs_fixer_level = "psr2"                 " which level ?
let g:php_cs_fixer_config = "default"             " configuration
let g:php_cs_fixer_php_path = "php"               " Path to PHP

" If you want to define specific fixers:
"let g:php_cs_fixer_fixers_list = "linefeed,short_tag,indentation"

" Enable the mapping by default (<leader>pcd for dir, <leader>pcf for file)
" let g:php_cs_fixer_enable_default_mapping = 1

" Custom mapping
:command PCD :call PhpCsFixerFixDirectory()<CR>
:command PCF :call PhpCsFixerFixFile()<CR>

let g:php_cs_fixer_dry_run = 0                    " Call command with dry-run option
let g:php_cs_fixer_verbose = 0                    " Return the output of command if 1, else an inline information.



"" Syntastic

" let g:syntastic_loc_list_height = 5
" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '∆'
let g:syntastic_style_error_symbol = '✠'
let g:syntastic_style_warning_symbol = '≈'

let g:syntastic_cursor_column = 0

" PHP
let g:syntastic_php_checkers=['php', 'phpcs']
let g:syntastic_php_phpcs_args="--standard=psr2"

" JavaScript
let g:syntastic_javascript_checkers = ['eslint']



"" Gundo
let g:gundo_width = 60
let g:gundo_preview_height = 20



"" AutoPairs

" Flymode: if(a[3) results in: if(a[3])
let g:AutoPairsFlyMode = 1

" https://github.com/jiangmiao/auto-pairs/issues/88
let g:AutoPairsShortcutFastWrap=''



"" vim-jsx

" Enable JSX syntax highlighting for .js files
let g:jsx_ext_required = 0



"" .vimrc editing

" Automatically source .vimrc when saving
augroup autosourcing
        autocmd!
        autocmd BufWritePost .vimrc source %
augroup END
